package com.mhy.shopingphone.model.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mhy.shopingphone.model.bean.greendao.bean.BannerListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANNER_LIST_BEAN".
*/
public class BannerListBeanDao extends AbstractDao<BannerListBean, Long> {

    public static final String TABLENAME = "BANNER_LIST_BEAN";

    /**
     * Properties of entity BannerListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BannerUrl = new Property(1, String.class, "bannerUrl", false, "BANNER_URL");
        public final static Property StrUrl = new Property(2, String.class, "strUrl", false, "STR_URL");
    }


    public BannerListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BannerListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANNER_LIST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BANNER_URL\" TEXT," + // 1: bannerUrl
                "\"STR_URL\" TEXT);"); // 2: strUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANNER_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BannerListBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bannerUrl = entity.getBannerUrl();
        if (bannerUrl != null) {
            stmt.bindString(2, bannerUrl);
        }
 
        String strUrl = entity.getStrUrl();
        if (strUrl != null) {
            stmt.bindString(3, strUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BannerListBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bannerUrl = entity.getBannerUrl();
        if (bannerUrl != null) {
            stmt.bindString(2, bannerUrl);
        }
 
        String strUrl = entity.getStrUrl();
        if (strUrl != null) {
            stmt.bindString(3, strUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BannerListBean readEntity(Cursor cursor, int offset) {
        BannerListBean entity = new BannerListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bannerUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // strUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BannerListBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBannerUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStrUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BannerListBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BannerListBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BannerListBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
