package com.mhy.shopingphone.model.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mhy.shopingphone.model.bean.greendao.bean.BannerListBean;

import com.mhy.shopingphone.model.bean.greendao.BannerListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerListBeanDaoConfig;

    private final BannerListBeanDao bannerListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerListBeanDaoConfig = daoConfigMap.get(BannerListBeanDao.class).clone();
        bannerListBeanDaoConfig.initIdentityScope(type);

        bannerListBeanDao = new BannerListBeanDao(bannerListBeanDaoConfig, this);

        registerDao(BannerListBean.class, bannerListBeanDao);
    }
    
    public void clear() {
        bannerListBeanDaoConfig.clearIdentityScope();
    }

    public BannerListBeanDao getBannerListBeanDao() {
        return bannerListBeanDao;
    }

}
